/*
 * Lexical data. Nouns appear in English and are never declined; they carry only a Polish
 * class tag (which fixes agreement) and coarse semantic tags (which keep collocations sane).
 * Adjectives are lemma + stem type; every form is generated by declension.js.
 *
 * Semantic tags: person, animal, thing, food, drink, place.
 */
(function (root) {
  'use strict';

  const P = 'person', A = 'animal', T = 'thing', F = 'food', D = 'drink', L = 'place';
  const ALL = [P, A, T, F, D, L];

  // mass: true → singular only (no natural English/Polish plural in these frames).
  // seed: true → from the original seed set; the rest are from the Duolingo export and
  // exist mainly so that e.g. every masc.-inanimate cell isn't always "table".
  const NOUNS = [
    // męskoosobowy — note mężczyzna is an -a noun but masc. personal: ten stary mężczyzna
    { en: 'man', pl: 'men', pol: 'mężczyzna', cls: 'męskoosobowy', sem: [P], seed: true },
    { en: 'boy', pl: 'boys', pol: 'chłopiec', cls: 'męskoosobowy', sem: [P], seed: true },
    { en: 'brother', pl: 'brothers', pol: 'brat', cls: 'męskoosobowy', sem: [P] },
    { en: 'student', pl: 'students', pol: 'student', cls: 'męskoosobowy', sem: [P] },

    // męskozwierzęcy — acc. sg. = gen. (tego psa), but plural is NON-virile (te psy)
    { en: 'cat', pl: 'cats', pol: 'kot', cls: 'męskozwierzęcy', sem: [A], seed: true },
    { en: 'dog', pl: 'dogs', pol: 'pies', cls: 'męskozwierzęcy', sem: [A], seed: true },
    { en: 'horse', pl: 'horses', pol: 'koń', cls: 'męskozwierzęcy', sem: [A], seed: true },
    { en: 'bird', pl: 'birds', pol: 'ptak', cls: 'męskozwierzęcy', sem: [A] },
    { en: 'lion', pl: 'lions', pol: 'lew', cls: 'męskozwierzęcy', sem: [A] },

    // męskorzeczowy
    { en: 'table', pl: 'tables', pol: 'stół', cls: 'męskorzeczowy', sem: [T], seed: true },
    { en: 'phone', pl: 'phones', pol: 'telefon', cls: 'męskorzeczowy', sem: [T] },
    { en: 'computer', pl: 'computers', pol: 'komputer', cls: 'męskorzeczowy', sem: [T] },
    { en: 'house', pl: 'houses', pol: 'dom', cls: 'męskorzeczowy', sem: [L] },
    { en: 'room', pl: 'rooms', pol: 'pokój', cls: 'męskorzeczowy', sem: [L] },
    { en: 'juice', pol: 'sok', cls: 'męskorzeczowy', sem: [D], mass: true },
    { en: 'bread', pol: 'chleb', cls: 'męskorzeczowy', sem: [F], mass: true },
    // Deliberately absent: tomato (pomidor) — colloquially takes animate acc. (jem pomidora),
    // so its agreement class is contested; bad material for a drill with one right answer.

    // żeński
    { en: 'woman', pl: 'women', pol: 'kobieta', cls: 'żeński', sem: [P], seed: true },
    { en: 'girl', pl: 'girls', pol: 'dziewczynka', cls: 'żeński', sem: [P], seed: true },
    { en: 'soup', pl: 'soups', pol: 'zupa', cls: 'żeński', sem: [F], seed: true },
    { en: 'coffee', pol: 'kawa', cls: 'żeński', sem: [D], seed: true, mass: true },
    { en: 'fish', pl: 'fish', pol: 'ryba', cls: 'żeński', sem: [A, F], seed: true },
    { en: 'school', pl: 'schools', pol: 'szkoła', cls: 'żeński', sem: [L], seed: true }, // not neuter!
    { en: 'book', pl: 'books', pol: 'książka', cls: 'żeński', sem: [T] },
    { en: 'bag', pl: 'bags', pol: 'torba', cls: 'żeński', sem: [T] },
    { en: 'mouse', pl: 'mice', pol: 'mysz', cls: 'żeński', sem: [A] }, // consonant-final, still fem.
    { en: 'duck', pl: 'ducks', pol: 'kaczka', cls: 'żeński', sem: [A] },
    { en: 'sandwich', pl: 'sandwiches', pol: 'kanapka', cls: 'żeński', sem: [F] },
    { en: 'water', pol: 'woda', cls: 'żeński', sem: [D], mass: true },
    { en: 'tea', pol: 'herbata', cls: 'żeński', sem: [D], mass: true },

    // nijaki
    { en: 'apple', pl: 'apples', pol: 'jabłko', cls: 'nijaki', sem: [F], seed: true },
    { en: 'food', pol: 'jedzenie', cls: 'nijaki', sem: [F], seed: true, mass: true },
    // dziecko: neuter sg., and dzieci is non-virile despite denoting people (te małe dzieci)
    { en: 'child', pl: 'children', pol: 'dziecko', cls: 'nijaki', sem: [P] },
    { en: 'animal', pl: 'animals', pol: 'zwierzę', cls: 'nijaki', sem: [A] },
    { en: 'window', pl: 'windows', pol: 'okno', cls: 'nijaki', sem: [T] },
    { en: 'bed', pl: 'beds', pol: 'łóżko', cls: 'nijaki', sem: [T] },
    { en: 'chair', pl: 'chairs', pol: 'krzesło', cls: 'nijaki', sem: [T] },
    { en: 'egg', pl: 'eggs', pol: 'jajko', cls: 'nijaki', sem: [F] },
    { en: 'wine', pol: 'wino', cls: 'nijaki', sem: [D], mass: true },
    { en: 'milk', pol: 'mleko', cls: 'nijaki', sem: [D], mass: true },
  ];

  // stem: hard (-y) | velar (-ki/-gi) | soft (-i after a non-velar, e.g. tani)
  // virile: override for a virile nom. pl. the alternation rules can't produce.
  // attested: all forms seen in the Duolingo export (vs. lemma only).
  const HUMAN_ISH = [P, A];
  const COLOR = [A, T, F, D];
  const ADJECTIVES = [
    { lemma: 'dobry', stem: 'hard', en: 'good', sem: ALL, attested: true },
    { lemma: 'zły', stem: 'hard', en: 'bad', sem: ALL, attested: true },
    { lemma: 'mały', stem: 'hard', en: 'small', sem: ALL, attested: true },
    { lemma: 'duży', stem: 'hard', en: 'big', sem: ALL, attested: true },
    { lemma: 'nowy', stem: 'hard', en: 'new', sem: ALL, attested: true },
    { lemma: 'stary', stem: 'hard', en: 'old', sem: ALL, attested: true },
    { lemma: 'smaczny', stem: 'hard', en: 'tasty', sem: [F, D], attested: true },

    { lemma: 'plastikowy', stem: 'hard', en: 'plastic', sem: [T] },
    { lemma: 'sławny', stem: 'hard', en: 'famous', sem: [P, A, L] },
    { lemma: 'wąski', stem: 'velar', en: 'narrow', sem: [T, L] },
    { lemma: 'metalowy', stem: 'hard', en: 'metal', sem: [T] },
    { lemma: 'szeroki', stem: 'velar', en: 'wide', sem: [T, L] },
    { lemma: 'drewniany', stem: 'hard', en: 'wooden', sem: [T] },
    { lemma: 'wesoły', stem: 'hard', en: 'cheerful', sem: HUMAN_ISH, virile: 'weseli' },
    { lemma: 'smutny', stem: 'hard', en: 'sad', sem: HUMAN_ISH },
    { lemma: 'suchy', stem: 'hard', en: 'dry', sem: [P, A, T, F] },
    { lemma: 'mokry', stem: 'hard', en: 'wet', sem: [P, A, T, F] },
    { lemma: 'słaby', stem: 'hard', en: 'weak', sem: [P, A, D] },
    { lemma: 'silny', stem: 'hard', en: 'strong', sem: [P, A, D] },
    { lemma: 'ciekawy', stem: 'hard', en: 'interesting', sem: [P, T, L] },
    { lemma: 'darmowy', stem: 'hard', en: 'free', sem: [T, F, D] },
    { lemma: 'nudny', stem: 'hard', en: 'boring', sem: [P, T, L] },
    { lemma: 'wygodny', stem: 'hard', en: 'comfortable', sem: [T, L] },
    { lemma: 'drogi', stem: 'velar', en: 'expensive', sem: [A, T, F, D, L] },
    { lemma: 'tani', stem: 'soft', en: 'cheap', sem: [A, T, F, D, L] },
    { lemma: 'ciężki', stem: 'velar', en: 'heavy', sem: [A, T, F] },
    { lemma: 'krótki', stem: 'velar', en: 'short', sem: [T] },
    { lemma: 'lekki', stem: 'velar', en: 'light', sem: [T, F, D] },
    { lemma: 'piękny', stem: 'hard', en: 'beautiful', sem: [P, A, T, L] },
    { lemma: 'długi', stem: 'velar', en: 'long', sem: [T] },
    { lemma: 'brzydki', stem: 'velar', en: 'ugly', sem: [P, A, T, L] },
    { lemma: 'wspaniały', stem: 'hard', en: 'wonderful', sem: ALL },
    { lemma: 'młody', stem: 'hard', en: 'young', sem: HUMAN_ISH },
    { lemma: 'wysoki', stem: 'velar', en: 'tall', sem: [P, A, T, L] },
    { lemma: 'popularny', stem: 'hard', en: 'popular', sem: [P, T, F, D, L] },
    { lemma: 'niski', stem: 'velar', en: 'short', sem: [P, A, T] },
    { lemma: 'miły', stem: 'hard', en: 'nice', sem: [P, A, L] },
    { lemma: 'jasny', stem: 'hard', en: 'bright', sem: [T, L] },
    { lemma: 'cały', stem: 'hard', en: 'whole', sem: [T, F, D, L] },
    { lemma: 'idealny', stem: 'hard', en: 'perfect', sem: ALL },
    { lemma: 'brudny', stem: 'hard', en: 'dirty', sem: [P, A, T, D, L] },
    { lemma: 'ciemny', stem: 'hard', en: 'dark', sem: [T, L] },
    { lemma: 'czysty', stem: 'hard', en: 'clean', sem: [P, A, T, D, L] },
    { lemma: 'normalny', stem: 'hard', en: 'normal', sem: [P, A, T, F, L] },
    { lemma: 'następny', stem: 'hard', en: 'next', sem: ALL },
    { lemma: 'bogaty', stem: 'hard', en: 'rich', sem: [P] },
    { lemma: 'biedny', stem: 'hard', en: 'poor', sem: HUMAN_ISH },
    { lemma: 'ważny', stem: 'hard', en: 'important', sem: [P, T, L] },
    { lemma: 'poprzedni', stem: 'soft', en: 'previous', sem: ALL },
    { lemma: 'inny', stem: 'hard', en: 'other', sem: ALL },
    { lemma: 'kolorowy', stem: 'hard', en: 'colourful', sem: COLOR },
    { lemma: 'fioletowy', stem: 'hard', en: 'purple', sem: COLOR },
    { lemma: 'szary', stem: 'hard', en: 'grey', sem: COLOR },
    { lemma: 'brązowy', stem: 'hard', en: 'brown', sem: COLOR },
    { lemma: 'pomarańczowy', stem: 'hard', en: 'orange', sem: COLOR },
    { lemma: 'różowy', stem: 'hard', en: 'pink', sem: COLOR },
    { lemma: 'biały', stem: 'hard', en: 'white', sem: COLOR },
    { lemma: 'czerwony', stem: 'hard', en: 'red', sem: COLOR },
    { lemma: 'czarny', stem: 'hard', en: 'black', sem: COLOR },
    { lemma: 'żółty', stem: 'hard', en: 'yellow', sem: COLOR },
    { lemma: 'niebieski', stem: 'velar', en: 'blue', sem: COLOR },
    { lemma: 'zielony', stem: 'hard', en: 'green', sem: COLOR },
  ];

  const api = { SEM: { P, A, T, F, D, L, ALL }, NOUNS, ADJECTIVES };

  if (typeof module === 'object' && module.exports) module.exports = api;
  else (root.MR = root.MR || {}).data = api;
})(this);
