/*
 * Lexical data. Nouns carry a Polish class tag (which fixes agreement), coarse semantic tags
 * (which keep collocations sane) and a full hand-written paradigm (the drilled forms).
 * Adjectives are lemma + stem type; every form is generated by declension.js.
 *
 * Semantic tags: person, animal, thing, food, drink, place.
 */
(function (root) {
  'use strict';

  const P = 'person', A = 'animal', T = 'thing', F = 'food', D = 'drink', L = 'place';
  const ALL = [P, A, T, F, D, L];

  // Nouns are the drilled item: each carries a hand-written paradigm, because Polish noun
  // endings are lexically conditioned (gen. sg. -a/-u, loc. sg. stem alternations like
  // stół → stole, suppletive plurals like brat → bracia) and can't be generated reliably.
  //
  // decl.sg / decl.pl: six forms in the order nom gen dat acc ins loc.
  // mass: true → singular only (no plural paradigm, never used in plural slots).
  // seed: true → from the original seed set; the rest come from the Duolingo export.
  const n = (en, pl, cls, sem, sg, plForms, extra) => Object.assign({
    en, pl, pol: sg.split(' ')[0], cls, sem,
    decl: { sg: sg.split(' '), pl: plForms ? plForms.split(' ') : null },
  }, extra);
  const mass = (en, cls, sem, sg, extra) => n(en, null, cls, sem, sg, null, Object.assign({ mass: true }, extra));
  const seed = { seed: true };

  const NOUNS = [
    // męskoosobowy — mężczyzna is an -a noun but masc. personal; acc. pl. = gen. pl.
    n('man', 'men', 'męskoosobowy', [P],
      'mężczyzna mężczyzny mężczyźnie mężczyznę mężczyzną mężczyźnie',
      'mężczyźni mężczyzn mężczyznom mężczyzn mężczyznami mężczyznach', seed),
    n('boy', 'boys', 'męskoosobowy', [P],
      'chłopiec chłopca chłopcu chłopca chłopcem chłopcu',
      'chłopcy chłopców chłopcom chłopców chłopcami chłopcach', seed),
    n('brother', 'brothers', 'męskoosobowy', [P],
      'brat brata bratu brata bratem bracie',
      'bracia braci braciom braci braćmi braciach'),
    n('student', 'students', 'męskoosobowy', [P],
      'student studenta studentowi studenta studentem studencie',
      'studenci studentów studentom studentów studentami studentach'),

    // męskozwierzęcy — acc. sg. = gen. (psa), but acc. pl. = nom. pl. (psy): non-virile
    n('cat', 'cats', 'męskozwierzęcy', [A],
      'kot kota kotu kota kotem kocie',
      'koty kotów kotom koty kotami kotach', seed),
    n('dog', 'dogs', 'męskozwierzęcy', [A],
      'pies psa psu psa psem psie',
      'psy psów psom psy psami psach', seed),
    n('horse', 'horses', 'męskozwierzęcy', [A],
      'koń konia koniowi konia koniem koniu',
      'konie koni koniom konie końmi koniach', seed),
    n('bird', 'birds', 'męskozwierzęcy', [A],
      'ptak ptaka ptakowi ptaka ptakiem ptaku',
      'ptaki ptaków ptakom ptaki ptakami ptakach'),
    n('lion', 'lions', 'męskozwierzęcy', [A],
      'lew lwa lwu lwa lwem lwie',
      'lwy lwów lwom lwy lwami lwach'),

    // męskorzeczowy — acc. = nom.; gen. sg. -a vs -u is lexical (stołu, komputera)
    n('table', 'tables', 'męskorzeczowy', [T],
      'stół stołu stołowi stół stołem stole',
      'stoły stołów stołom stoły stołami stołach', seed),
    n('phone', 'phones', 'męskorzeczowy', [T],
      'telefon telefonu telefonowi telefon telefonem telefonie',
      'telefony telefonów telefonom telefony telefonami telefonach'),
    n('computer', 'computers', 'męskorzeczowy', [T],
      'komputer komputera komputerowi komputer komputerem komputerze',
      'komputery komputerów komputerom komputery komputerami komputerach'),
    n('house', 'houses', 'męskorzeczowy', [L],
      'dom domu domowi dom domem domu',
      'domy domów domom domy domami domach'),
    // gen. pl. pokoi ~ pokojów: both standard; pokoi used, pokojów never offered as a distractor
    n('room', 'rooms', 'męskorzeczowy', [L],
      'pokój pokoju pokojowi pokój pokojem pokoju',
      'pokoje pokoi pokojom pokoje pokojami pokojach'),
    mass('juice', 'męskorzeczowy', [D], 'sok soku sokowi sok sokiem soku'),
    mass('bread', 'męskorzeczowy', [F], 'chleb chleba chlebowi chleb chlebem chlebie'),
    // Deliberately absent: tomato (pomidor) — colloquially takes animate acc. (jem pomidora),
    // so its agreement class is contested; bad material for a drill with one right answer.

    // żeński
    n('woman', 'women', 'żeński', [P],
      'kobieta kobiety kobiecie kobietę kobietą kobiecie',
      'kobiety kobiet kobietom kobiety kobietami kobietach', seed),
    n('girl', 'girls', 'żeński', [P],
      'dziewczynka dziewczynki dziewczynce dziewczynkę dziewczynką dziewczynce',
      'dziewczynki dziewczynek dziewczynkom dziewczynki dziewczynkami dziewczynkach', seed),
    n('soup', 'soups', 'żeński', [F],
      'zupa zupy zupie zupę zupą zupie',
      'zupy zup zupom zupy zupami zupach', seed),
    mass('coffee', 'żeński', [D], 'kawa kawy kawie kawę kawą kawie', seed),
    n('fish', 'fish', 'żeński', [A, F],
      'ryba ryby rybie rybę rybą rybie',
      'ryby ryb rybom ryby rybami rybach', seed),
    n('school', 'schools', 'żeński', [L], // not neuter!
      'szkoła szkoły szkole szkołę szkołą szkole',
      'szkoły szkół szkołom szkoły szkołami szkołach', seed),
    n('book', 'books', 'żeński', [T],
      'książka książki książce książkę książką książce',
      'książki książek książkom książki książkami książkach'),
    n('bag', 'bags', 'żeński', [T],
      'torba torby torbie torbę torbą torbie',
      'torby toreb torbom torby torbami torbach'),
    n('mouse', 'mice', 'żeński', [A], // consonant-final, still fem.; heavy -y syncretism
      'mysz myszy myszy mysz myszą myszy',
      'myszy myszy myszom myszy myszami myszach'),
    n('duck', 'ducks', 'żeński', [A],
      'kaczka kaczki kaczce kaczkę kaczką kaczce',
      'kaczki kaczek kaczkom kaczki kaczkami kaczkach'),
    n('sandwich', 'sandwiches', 'żeński', [F],
      'kanapka kanapki kanapce kanapkę kanapką kanapce',
      'kanapki kanapek kanapkom kanapki kanapkami kanapkach'),
    mass('water', 'żeński', [D], 'woda wody wodzie wodę wodą wodzie'),
    mass('tea', 'żeński', [D], 'herbata herbaty herbacie herbatę herbatą herbacie'),

    // nijaki — acc. = nom. in both numbers
    n('apple', 'apples', 'nijaki', [F],
      'jabłko jabłka jabłku jabłko jabłkiem jabłku',
      'jabłka jabłek jabłkom jabłka jabłkami jabłkach', seed),
    mass('food', 'nijaki', [F], 'jedzenie jedzenia jedzeniu jedzenie jedzeniem jedzeniu', seed),
    // dziecko: neuter sg.; dzieci is non-virile despite denoting people (te małe dzieci)
    n('child', 'children', 'nijaki', [P],
      'dziecko dziecka dziecku dziecko dzieckiem dziecku',
      'dzieci dzieci dzieciom dzieci dziećmi dzieciach'),
    n('animal', 'animals', 'nijaki', [A],
      'zwierzę zwierzęcia zwierzęciu zwierzę zwierzęciem zwierzęciu',
      'zwierzęta zwierząt zwierzętom zwierzęta zwierzętami zwierzętach'),
    n('window', 'windows', 'nijaki', [T],
      'okno okna oknu okno oknem oknie',
      'okna okien oknom okna oknami oknach'),
    n('bed', 'beds', 'nijaki', [T],
      'łóżko łóżka łóżku łóżko łóżkiem łóżku',
      'łóżka łóżek łóżkom łóżka łóżkami łóżkach'),
    n('chair', 'chairs', 'nijaki', [T],
      'krzesło krzesła krzesłu krzesło krzesłem krześle',
      'krzesła krzeseł krzesłom krzesła krzesłami krzesłach'),
    n('egg', 'eggs', 'nijaki', [F],
      'jajko jajka jajku jajko jajkiem jajku',
      'jajka jajek jajkom jajka jajkami jajkach'),
    mass('wine', 'nijaki', [D], 'wino wina winu wino winem winie'),
    mass('milk', 'nijaki', [D], 'mleko mleka mleku mleko mlekiem mleku'),
  ];

  // stem: hard (-y) | velar (-ki/-gi) | soft (-i after a non-velar, e.g. tani)
  // virile: override for a virile nom. pl. the alternation rules can't produce.
  // attested: all forms seen in the Duolingo export (vs. lemma only).
  const HUMAN_ISH = [P, A];
  const COLOR = [A, T, F, D];
  const ADJECTIVES = [
    { lemma: 'dobry', stem: 'hard', en: 'good', sem: ALL, attested: true },
    { lemma: 'zły', stem: 'hard', en: 'bad', sem: ALL, attested: true },
    { lemma: 'mały', stem: 'hard', en: 'small', sem: ALL, attested: true },
    { lemma: 'duży', stem: 'hard', en: 'big', sem: ALL, attested: true },
    { lemma: 'nowy', stem: 'hard', en: 'new', sem: ALL, attested: true },
    { lemma: 'stary', stem: 'hard', en: 'old', sem: ALL, attested: true },
    { lemma: 'smaczny', stem: 'hard', en: 'tasty', sem: [F, D], attested: true },

    { lemma: 'plastikowy', stem: 'hard', en: 'plastic', sem: [T] },
    { lemma: 'sławny', stem: 'hard', en: 'famous', sem: [P, A, L] },
    { lemma: 'wąski', stem: 'velar', en: 'narrow', sem: [T, L] },
    { lemma: 'metalowy', stem: 'hard', en: 'metal', sem: [T] },
    { lemma: 'szeroki', stem: 'velar', en: 'wide', sem: [T, L] },
    { lemma: 'drewniany', stem: 'hard', en: 'wooden', sem: [T] },
    { lemma: 'wesoły', stem: 'hard', en: 'cheerful', sem: HUMAN_ISH, virile: 'weseli' },
    { lemma: 'smutny', stem: 'hard', en: 'sad', sem: HUMAN_ISH },
    { lemma: 'suchy', stem: 'hard', en: 'dry', sem: [P, A, T, F] },
    { lemma: 'mokry', stem: 'hard', en: 'wet', sem: [P, A, T, F] },
    { lemma: 'słaby', stem: 'hard', en: 'weak', sem: [P, A, D] },
    { lemma: 'silny', stem: 'hard', en: 'strong', sem: [P, A, D] },
    { lemma: 'ciekawy', stem: 'hard', en: 'interesting', sem: [P, T, L] },
    { lemma: 'darmowy', stem: 'hard', en: 'free', sem: [T, F, D] },
    { lemma: 'nudny', stem: 'hard', en: 'boring', sem: [P, T, L] },
    { lemma: 'wygodny', stem: 'hard', en: 'comfortable', sem: [T, L] },
    { lemma: 'drogi', stem: 'velar', en: 'expensive', sem: [A, T, F, D, L] },
    { lemma: 'tani', stem: 'soft', en: 'cheap', sem: [A, T, F, D, L] },
    { lemma: 'ciężki', stem: 'velar', en: 'heavy', sem: [A, T, F] },
    { lemma: 'krótki', stem: 'velar', en: 'short', sem: [T] },
    { lemma: 'lekki', stem: 'velar', en: 'light', sem: [T, F, D] },
    { lemma: 'piękny', stem: 'hard', en: 'beautiful', sem: [P, A, T, L] },
    { lemma: 'długi', stem: 'velar', en: 'long', sem: [T] },
    { lemma: 'brzydki', stem: 'velar', en: 'ugly', sem: [P, A, T, L] },
    { lemma: 'wspaniały', stem: 'hard', en: 'wonderful', sem: ALL },
    { lemma: 'młody', stem: 'hard', en: 'young', sem: HUMAN_ISH },
    { lemma: 'wysoki', stem: 'velar', en: 'tall', sem: [P, A, T, L] },
    { lemma: 'popularny', stem: 'hard', en: 'popular', sem: [P, T, F, D, L] },
    { lemma: 'niski', stem: 'velar', en: 'short', sem: [P, A, T] },
    { lemma: 'miły', stem: 'hard', en: 'nice', sem: [P, A, L] },
    { lemma: 'jasny', stem: 'hard', en: 'bright', sem: [T, L] },
    { lemma: 'cały', stem: 'hard', en: 'whole', sem: [T, F, D, L] },
    { lemma: 'idealny', stem: 'hard', en: 'perfect', sem: ALL },
    { lemma: 'brudny', stem: 'hard', en: 'dirty', sem: [P, A, T, D, L] },
    { lemma: 'ciemny', stem: 'hard', en: 'dark', sem: [T, L] },
    { lemma: 'czysty', stem: 'hard', en: 'clean', sem: [P, A, T, D, L] },
    { lemma: 'normalny', stem: 'hard', en: 'normal', sem: [P, A, T, F, L] },
    { lemma: 'następny', stem: 'hard', en: 'next', sem: ALL },
    { lemma: 'bogaty', stem: 'hard', en: 'rich', sem: [P] },
    { lemma: 'biedny', stem: 'hard', en: 'poor', sem: HUMAN_ISH },
    { lemma: 'ważny', stem: 'hard', en: 'important', sem: [P, T, L] },
    { lemma: 'poprzedni', stem: 'soft', en: 'previous', sem: ALL },
    { lemma: 'inny', stem: 'hard', en: 'other', sem: ALL },
    { lemma: 'kolorowy', stem: 'hard', en: 'colourful', sem: COLOR },
    { lemma: 'fioletowy', stem: 'hard', en: 'purple', sem: COLOR },
    { lemma: 'szary', stem: 'hard', en: 'grey', sem: COLOR },
    { lemma: 'brązowy', stem: 'hard', en: 'brown', sem: COLOR },
    { lemma: 'pomarańczowy', stem: 'hard', en: 'orange', sem: COLOR },
    { lemma: 'różowy', stem: 'hard', en: 'pink', sem: COLOR },
    { lemma: 'biały', stem: 'hard', en: 'white', sem: COLOR },
    { lemma: 'czerwony', stem: 'hard', en: 'red', sem: COLOR },
    { lemma: 'czarny', stem: 'hard', en: 'black', sem: COLOR },
    { lemma: 'żółty', stem: 'hard', en: 'yellow', sem: COLOR },
    { lemma: 'niebieski', stem: 'velar', en: 'blue', sem: COLOR },
    { lemma: 'zielony', stem: 'hard', en: 'green', sem: COLOR },
  ];

  const api = { SEM: { P, A, T, F, D, L, ALL }, NOUNS, ADJECTIVES };

  if (typeof module === 'object' && module.exports) module.exports = api;
  else (root.MR = root.MR || {}).data = api;
})(this);
